version: '3.5'

services:
  homage_server:
    container_name: homage_server

    restart: always

    build:
      context: .
      target: development

    ports:
      - 3000:3000

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest

    restart: always

    environment:
      POSTGRES_DATABASE: homage
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    container_name: postgresql

    ports:
      - "5432:5432"
